services:
  build:
#    command:
#      - --debug
    environment:
      CONTEXT: production
      URL: https://accio.subtlecoolness.com
    image: ghcr.io/williamjacksn/pelican:4.8.0
    init: true
    volumes:
      - ./:/pelican-site

  dev:
    command:
      - --autoreload
      - --listen
    image: ghcr.io/williamjacksn/pelican:4.8.0
    init: true
    ports:
      - 8000:8000
    volumes:
      - ./:/pelican-site

  clean:
    command:
      - -f
      - -r
      - __pycache__
      - cache
      - output
    entrypoint:
      - /bin/rm
    image: ghcr.io/williamjacksn/pelican:4.8.0
    init: true
    volumes:
      - ./:/pelican-site
