[build]
command = "pelican"
publish = "output"

[build.environment]
NODE_VERSION = "14.17.0"
PIP_DISABLE_PIP_VERSION_CHECK = "yes"

[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'none'; base-uri 'none'; connect-src https://404.subtlecoolness.com; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self'"
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"

[[plugins]]
package = "netlify-plugin-out-of-minutes"
